### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(TaidaFlow)
add_subdirectory(TaidaFlowContent)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    TaidaFlowplugin
    TaidaFlowContentplugin
    QtQuickDesignerComponents)