#pragma once

#include <QString>

// Embedded CJK font support.
//
// Qt for WebAssembly has no access to the operating system's fonts; only the
// few Latin fonts bundled with Qt are available, so every Traditional Chinese
// glyph in the UI would render as a box. The application therefore embeds a
// Noto Sans TC subset (OFL-1.1, generated by scripts/make_font_subset.py and
// compiled into the :/fonts resource) and, on WebAssembly, wires it into the
// font fallback chain.
namespace TaidaFlowFonts {

// Registers the embedded subset (Regular + Bold) with QFontDatabase.
// Returns the family name, or an empty string if loading failed.
QString loadEmbeddedCjkFont();

// Makes `family` the glyph fallback for every family the UI requests
// (application default, Qt Quick Controls Universal "Segoe UI", "Consolas", ...)
// via QFont::insertSubstitutions, and registers it as the application fallback
// for the Han script. Must run after QApplication and before the QML engine loads.
void installCjkFallbackChain(const QString &family);

} // namespace TaidaFlowFonts
